modLoader="javafml"
loaderVersion="[46,)"
logoFile="icon.png"
license="ARR"

[[mods]]
	modId="bcb"
	version="${file.jarVersion}"
	displayName="Benchmark Compressed Blocks"
	description='''Compressed Blocks mod'''
	displayURL="http://curseforge.com/minecraft/mc-mods/benchmark-compressed-blocks"
	authors="BenchmarkTeam"

[[dependencies.bcb]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bcb]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"